version: "3.9"

services:
  proxy:
    image: nginx
    container_name: proxy
    depends_on:
      - dummy1
      - dummy2
    networks:
      - dummy1
      - dummy2
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/public:/var/www/html
      - ./nginx/includes:/etc/nginx/includes
      - ./nginx/vhosts:/etc/nginx/vhosts
      - ./nginx/shared:/etc/nginx/shared
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
  certbot:
    container_name: certbot
    image: certbot/certbot
    restart: unless-stopped
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
  dummy1:
    image: maxseliverstov/nginx-dummy1_amd64
    container_name: dummy1
    networks:
      dummy1:
  dummy2:
    image: maxseliverstov/nginx-dummy2_amd64
    container_name: dummy2
    networks:
      dummy2:

networks:
  dummy1:
  dummy2:
